[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "zhyjgfndwnvbbahj"
email = "741541779@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
databaseName = "GopherAI"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "GopherAI"
 key= "GopherAI-v1"

 [rabbitmqConfig]
  host= "127.0.0.1"
  port= 5672
  username= "guest"
  password= "guest"
  vhost= "/"

[aiConfig]
# OpenAI配置
openai_api_key = "sk-0d186267e37344b98abd5daa99c3b8ef"
openai_model_name = "deepseek-chat"
openai_base_url = "https://api.deepseek.com/v1"
# Ollama配置
ollama_base_url = "http://localhost:11434"
ollama_model_name = "llama3"
# 默认模型类型 1:OpenAI 2:Ollama
default_model_type = "1"
